---
title: "Untitled"
output: html_document
---

```{r}
run_byline<-readLines("C:/Users/12055/Downloads/run example.txt")
?readLines

dtm_run<-function(){
#detect new lines to use as rows using "\n"
  {
#break down the sentence into tokens
}
#final_tokenized_version<-}
  
#final_tokenized_version
  #sentence ...how to count the frequency ? 
  #0 1 0 = 1
  #1 0 1 = 2
  #1 1 1 = 3
  #within each cell stated frequency composed of added binary vectors 
```



```{r}
doc1<-run[1,]
doc2<-run[2,]
doc3<-run[3,]
traces<-cbind(doc1,doc2,doc3)

frequency<-function(x){
  for (i in x)
  { 
  for(j in x)
  {return(sum(as.numeric(x== "I")))
  }
  }}
frequency(traces)

class(uniqueterms)#factor
traces<-t(cbind("doc1","doc2","doc3"))
detectTerms<-as.factor(traces)

uniqueterms<-unique(detectTerms)
frequency<-function(x){
  for (i in x)
  { 
  for(j in x)
  {return(sum(as.numeric(x== uniqueterms)))
  }
  }
  }
frequency(traces)
    #evaluate for words  


 uniqueterms<-c("I", "run", "a", "lot", "what", "do", "think")
```

